title: cycool29's blog
description: "“Potential partners are like internet domain names — the ones I like are already taken.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap