title: cycool29's blog
description: "“When I wrote this code, only God and I understood what I did. Now only God knows.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap