title: cycool29's blog
description: "“To understand what recursion is, you must first understand recursion.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap