title: cycool29's blog
comments: Comments
description: "“Q: Is the glass half-full or half-empty? A: The glass is twice as big as it needs to be.” "
remote_theme: jekyll-theme-hacker
author: cycool29
github:
    is_project_page: false
url: https://cycool29.github.io
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
timezone: UTC 
plugins:
  - jekyll-sitemap