title: cycool29's blog
description: "“UNIX is user friendly. It’s just very particular about who its friends are.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap