title: cycool29's blog
description: "“I have not failed. I’ve just found 10,000 ways that won’t work.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
