title: cycool29's blog
description: "“A program is never less than 90% complete and never more than 95% complete.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap