title: cycool29's blog
comments: Comments
description: “99 little bugs in the code. 99 little bugs in the code. Take one down, patch it around. 127 little bugs in the code …” 
remote_theme: jekyll-theme-hacker
github:
    is_project_page: false
