title: cycool29's blog
description: "“In C we had to code our own bugs. In C++ we can inherit them.” "
bio: "lol"
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
