title: cycool29's blog
description: "“Programming is like sex: One mistake and you have to support it for the rest of your life.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap