title: cycool29's blog
comments: Comments
description: "“Q: How different are C and C++? A: 1. Because C — C++ = 1.” "
remote_theme: jekyll-theme-hacker
author: cycool29
github:
    is_project_page: false
plugins:
  - jekyll-feed
plugins: ['jekyll-twitter-plugin']
