title: cycool29's blog
description: "“Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
