title: cycool29's blog
description: "“If Java had true garbage collection, most programs would delete themselves upon execution.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap