title: cycool29's blog
description: "“A good programmer is someone who always looks both ways before crossing a one-way street.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
