title: cycool29's blog
description: "“A system administrator has two problems: 1. Dumb users. 2. Smart users.” "
bio: "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
