title: cycool29's blog
description: "“Knock, knock … Who’s there? … *very long pause* … Java.”"
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
