title: cycool29's blog
description: "“UNIX is user friendly. It’s just very particular about who its friends are.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
