title: cycool29's blog
description: "“How many programmers does it take to change a light bulb? None, that’s a hardware problem.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
