title: cycool29's blog
description: "“Q: Is the glass half-full or half-empty? A: The glass is twice as big as it needs to be.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
