title: cycool29's blog
comments: Comments
description: "“God is real … unless declared integer.” "
remote_theme: jekyll-theme-hacker
author: cycool29
github:
    is_project_page: false
plugins:
  - jekyll-feed

