title: cycool29's blog
description: "“The best thing about a boolean is even if you are wrong, you are only off by a bit.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
