title: cycool29's blog
description: "“The best way to get accurate information on Usenet is to post something wrong and wait for corrections.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
