title: cycool29's blog
comments: Comments
description: "“A good programmer is someone who always looks both ways before crossing a one-way street.” "
remote_theme: jekyll-theme-hacker
author: cycool29
github:
    is_project_page: false
url: https://cycool29.github.io
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
