title: cycool29's blog
description: "“Programming is like sex: One mistake and you have to support it for the rest of your life.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
