title: cycool29's blog
description: "“Without C we only have Obol, Pasal, and BASI.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
