title: cycool29's blog
comments: Comments
description: "“Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.” "
remote_theme: jekyll-theme-hacker
author: cycool29
github:
    is_project_page: false
url: https://cycool29.github.io
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
timezone: UTC 
plugins:
  - jekyll-sitemap