title: cycool29's blog
comments: Comments
description: "“There are only two kinds of programming languages out there. The ones people complain about and the ones no one uses.” "
remote_theme: jekyll-theme-hacker
github:
    is_project_page: false
