title: cycool29's blog
description: "“There are 10 kinds of people in the world: Those who know binary and those who don’t.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap