title: cycool29's blog
description: "“.NET is called .NET so that it wouldn’t show up in a UNIX directory listing.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
