title: cycool29's blog
description: "“Why do Java programmers have to wear glasses? Because they don’t C#.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
