title: cycool29's blog
comments: Comments
description: "“Programming can be fun, and so can cryptography; however, they should not be combined.” "
remote_theme: jekyll-theme-hacker
author: cycool29
github:
    is_project_page: false
plugins:
  - jekyll-feed

