title: cycool29's blog
description: "“I’ve finally learned what upward compatible means. It means we get to keep all our old mistakes.” "
bio: "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
