title: cycool29's blog
description: "“Perl: The only language that looks the same before and after RSA encryption.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap