title: cycool29's blog
description: "“In a room full of top software designers, if two agree on the same thing, that’s a majority.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap