title: cycool29's blog
description: "“Algorithm: Word used by programmers when they don’t want to explain what they did.” "
bio: "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
