title: cycool29's blog
description: "“A SQL query goes into a bar, walks up to two tables, and asks, ‘Can I join you?’” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
