title: cycool29's blog
description: "“If debugging is the process of removing bugs, then programming must be the process of putting them in.” "
bio: "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
