title: cycool29's blog
description: "“Q: What did the Java code say to the C code? A: You’ve got no class.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
