title: cycool29's blog
description: "“Software undergoes beta testing shortly before it’s released. Beta is Latin for still doesn’t work.” "
bio: A high school student. Intermediate in Python, Git, Bash. Learning JavaScript. He/Him. "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
