title: cycool29's blog
description: "“Copy-and-Paste was programmed by programmers for programmers actually.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap