title: cycool29's blog
description: "“When we had no computers, we had no programming problems either.” "
bio: "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap
