title: cycool29's blog
description: "“Walking on water and developing software from a specification are easy if both are frozen.” "
author: cycool29
url: https://cycool29.github.io
timezone: UTC 
plugins:
  - jekyll-sitemap