name: Update bio
on:
  schedule: 
      - cron: '0 23 * * *'
  push:
    branches:    
      - 'gh-pages'
  workflow_dispatch:
jobs:
  update-quotes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update quotes 
        run: |
          sudo apt-get install jq wget -y
          bio="$(wget -qO- https://api.github.com/users/cycool29 | jq -r '.bio')"
          sed -i "s+bio:.*+bio: $bio"'"'"+g" _config.yml
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update bio"
          git push
