name: Update quotes
on:
  schedule: 
      - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  update-quotes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update quotes 
        run: |
          sed -i 's/description.*/description: "'"$( shuf -n 1 quotes)"'"/' _config.yml
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update quotes"
          git push
